[package]
name = "bcs"
version = "0.1.0"
authors = ["Giovannella"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

text_io = "0.1.0-pre"
rand = "0.3.14"